### ISSUE TITLE
missing jobmon dependency

### ISSUE THREAD

**Issue by aflaxman** [ihmeuw/covid-model-seiir-pipeline#253]
With a fresh install, this failed: `from covid_model_seiir_pipeline.pipeline.forecasting import model` with an error message I accidentally deleted.  The error message led me to this `covid_shared` package.  After I `pip install jobmon`, now my import works.

https://github.com/ihmeuw/covid-model-seiir-pipeline/blob/52c3ad2ffd8e429599cd3061ee9cdff1a849597d/setup.py#L42

**Comment by collijk** [comment]
This is intentional behavior to isolate the internal IHME dependencies so the automated test suite can run on github's servers.  Installation instructions have been updated on the develop branches README and will be merged to main after the next production run: https://github.com/ihmeuw/covid-model-seiir-pipeline/blob/develop/README.rst
